/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolApp;

import javax.swing.JTabbedPane;
import schoolApp.StudentDASHBOARD;
/**
 *
 * @author Iredafe
 */
public class StudentHome extends javax.swing.JFrame {

    /**
     * Creates new form StudentHome
     */
    public StudentHome() {
        initComponents();
    
    setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myExamsHome = new javax.swing.JButton();
        myAssignmentsHome = new javax.swing.JButton();
        mySubjectHome = new javax.swing.JButton();
        myScheduleHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        myGradesHome = new javax.swing.JButton();
        myGamesHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Iredafe\\Downloads\\young-student image.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 530, 520));

        myExamsHome.setBackground(new java.awt.Color(0, 153, 153));
        myExamsHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myExamsHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/exam.png"))); // NOI18N
        myExamsHome.setText("My Exams");
        myExamsHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myExamsHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myExamsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myExamsHomeActionPerformed(evt);
            }
        });
        jPanel1.add(myExamsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 160, 110));

        myAssignmentsHome.setBackground(new java.awt.Color(0, 153, 153));
        myAssignmentsHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myAssignmentsHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/homework (2).png"))); // NOI18N
        myAssignmentsHome.setText("My Assignments");
        myAssignmentsHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myAssignmentsHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myAssignmentsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAssignmentsHomeActionPerformed(evt);
            }
        });
        jPanel1.add(myAssignmentsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 160, 110));

        mySubjectHome.setBackground(new java.awt.Color(0, 153, 153));
        mySubjectHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        mySubjectHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Books-icon.png"))); // NOI18N
        mySubjectHome.setText("My Subjects");
        mySubjectHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mySubjectHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mySubjectHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySubjectHomeActionPerformed(evt);
            }
        });
        jPanel1.add(mySubjectHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 160, 120));

        myScheduleHome.setBackground(new java.awt.Color(0, 153, 153));
        myScheduleHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myScheduleHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/Apps-preferences-system-time-icon.png"))); // NOI18N
        myScheduleHome.setText("My Schedule");
        myScheduleHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myScheduleHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myScheduleHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myScheduleHomeActionPerformed(evt);
            }
        });
        jPanel1.add(myScheduleHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 160, 120));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Welcome To");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 210, 30));

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton5.setText("Log Out");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 550, -1, -1));

        myGradesHome.setBackground(new java.awt.Color(0, 153, 153));
        myGradesHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myGradesHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/score.png"))); // NOI18N
        myGradesHome.setText("My Grades");
        myGradesHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myGradesHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myGradesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGradesHomeActionPerformed(evt);
            }
        });
        jPanel1.add(myGradesHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 160, 120));

        myGamesHome.setBackground(new java.awt.Color(0, 153, 153));
        myGamesHome.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        myGamesHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolApp/schoolicons/folder-games-icon.png"))); // NOI18N
        myGamesHome.setText("My Games");
        myGamesHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myGamesHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myGamesHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myGamesHomeActionPerformed(evt);
            }
        });
        jPanel1.add(myGamesHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 160, 120));

        jLabel3.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ABC GROUP OF SCHOOLS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mySubjectHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySubjectHomeActionPerformed

dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);

        // TODO add your handling code here:



    }//GEN-LAST:event_mySubjectHomeActionPerformed

    private void myScheduleHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myScheduleHomeActionPerformed


dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_myScheduleHomeActionPerformed

    private void myAssignmentsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAssignmentsHomeActionPerformed


dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_myAssignmentsHomeActionPerformed

    private void myExamsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myExamsHomeActionPerformed


dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_myExamsHomeActionPerformed

    private void myGradesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGradesHomeActionPerformed

        
dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_myGradesHomeActionPerformed

    private void myGamesHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myGamesHomeActionPerformed


dispose();
StudentDASHBOARD sd = new StudentDASHBOARD();
        sd.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_myGamesHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton myAssignmentsHome;
    private javax.swing.JButton myExamsHome;
    private javax.swing.JButton myGamesHome;
    private javax.swing.JButton myGradesHome;
    private javax.swing.JButton myScheduleHome;
    private javax.swing.JButton mySubjectHome;
    // End of variables declaration//GEN-END:variables
}
